main: net.urbanmc.mcinfected.MCInfected
name: MCInfected
version: 1.1
authors: [Elian, Silverwolfg11]
depend: [ProtocolLib, LibsDisguises]
api-version: 1.16

permissions:
  command.about:
    default: true
  command.forcestart:
    default: op
  command.help:
    default: true
  command.ignore:
    default: true
  command.ignore.exempt:
    default: op
  command.infected:
    default: true
  command.kit:
    default: true
  command.list:
    default: true
  command.message:
    default: true
  command.reply:
    default: true
  command.shop:
    default: true
  command.sneak:
    default: op
  command.stats:
    default: true
  command.vote:
    default: true
  command.worldtp:
    default: op
  namecolor.aqua:
    default: false
  namecolor.gold:
    default: false
  namecolor.red:
    default: false
  chatcolor.pink:
    default: false
  chatcolor.green:
    default: false
  chatcolor.red:
    default: false
